"""Linear algebra utilities for vectors, matrices, and quaternions."""

# The imports below intentionally define the public package-level API.
# ruff: noqa: F401

from .vectors import add_vectors
from .vectors import add_vectors_xy
from .vectors import allclose
from .vectors import argmax
from .vectors import argmin
from .transformations import axis_and_angle_from_matrix
from .quaternions import axis_angle_from_quaternion
from .transformations import axis_angle_vector_from_matrix
from .transformations import basis_vectors_from_matrix
from .vectors import close
from .transformations import compose_matrix
from .vectors import cross_vectors
from .vectors import cross_vectors_xy
from .transformations import decompose_matrix
from .vectors import dehomogenize_vectors
from .vectors import divide_vectors
from .vectors import divide_vectors_xy
from .vectors import dot_vectors
from .vectors import dot_vectors_xy
from .transformations import euler_angles_from_matrix
from .quaternions import euler_angles_from_quaternion
from .vectors import homogenize_vectors
from .transformations import identity_matrix
from .matrices import is_matrix_square
from .vectors import length_vector
from .vectors import length_vector_sqrd
from .vectors import length_vector_sqrd_xy
from .vectors import length_vector_xy
from .matrices import matrix_determinant
from .transformations import matrix_from_axis_and_angle
from .transformations import matrix_from_axis_angle_vector
from .transformations import matrix_from_basis_vectors
from .transformations import matrix_from_change_of_basis
from .transformations import matrix_from_euler_angles
from .transformations import matrix_from_frame
from .transformations import matrix_from_frame_to_frame
from .transformations import matrix_from_orthogonal_projection
from .transformations import matrix_from_parallel_projection
from .transformations import matrix_from_perspective_entries
from .transformations import matrix_from_perspective_projection
from .transformations import matrix_from_quaternion
from .transformations import matrix_from_scale_factors
from .transformations import matrix_from_shear
from .transformations import matrix_from_shear_entries
from .transformations import matrix_from_translation
from .matrices import matrix_inverse
from .matrices import matrix_minor
from .matrices import multiply_matrices
from .matrices import multiply_matrix_vector
from .vectors import multiply_vectors
from .vectors import multiply_vectors_xy
from .vectors import norm_vector
from .vectors import norm_vectors
from .vectors import normalize_vector
from .vectors import normalize_vector_xy
from .vectors import normalize_vectors
from .vectors import normalize_vectors_xy
from .vectors import orthonormalize_vectors
from .vectors import power_vector
from .vectors import power_vectors
from .quaternions import quaternion_from_axis_angle
from .quaternions import quaternion_from_euler_angles
from .transformations import quaternion_from_matrix
from .vectors import scale_vector
from .vectors import scale_vector_xy
from .vectors import scale_vectors
from .vectors import scale_vectors_xy
from .vectors import square_vector
from .vectors import square_vectors
from .vectors import subtract_vectors
from .vectors import subtract_vectors_xy
from .vectors import sum_vectors
from .transformations import translation_from_matrix
from .matrices import transpose_matrix
from .vectors import vector_average
from .vectors import vector_component
from .vectors import vector_component_xy
from .vectors import vector_standard_deviation
from .vectors import vector_variance
from .decompositions import chofactor
from .decompositions import dof
from .decompositions import lufactorized
from .decompositions import memoize
from .decompositions import Memoized
from .decompositions import nonpivots
from .decompositions import normalizerow
from .decompositions import normrow
from .decompositions import nullspace
from .decompositions import pivots
from .decompositions import rank
from .decompositions import rot90
from .decompositions import rref
from .solvers import solve_with_known
from .solvers import spsolve_with_known
from .decompositions import uvw_lengths
from .operators import adjacency_matrix
from .operators import connectivity_matrix
from .operators import degree_matrix
from .operators import equilibrium_matrix
from .operators import face_matrix
from .operators import laplacian_matrix
from .operators import mass_matrix
from .operators import stiffness_matrix
from .quaternions import quaternion_canonize
from .quaternions import quaternion_conjugate
from .quaternions import quaternion_is_unit
from .quaternions import quaternion_multiply
from .quaternions import quaternion_norm
from .quaternions import quaternion_unitize
