COMPONENT_TYPE_BYTE = 5120
COMPONENT_TYPE_UNSIGNED_BYTE = 5121
COMPONENT_TYPE_SHORT = 5122
COMPONENT_TYPE_UNSIGNED_SHORT = 5123
COMPONENT_TYPE_UNSIGNED_INT = 5125
COMPONENT_TYPE_FLOAT = 5126

TYPE_SCALAR = "SCALAR"
TYPE_VEC2 = "VEC2"
TYPE_VEC3 = "VEC3"
TYPE_VEC4 = "VEC4"
TYPE_MAT2 = "MAT2"
TYPE_MAT3 = "MAT3"
TYPE_MAT4 = "MAT4"

MODE_POINTS = 0
MODE_LINES = 1
MODE_LINE_LOOP = 2
MODE_LINE_STRIP = 3
MODE_TRIANGLES = 4
MODE_TRIANGLE_STRIP = 5
MODE_TRIANGLE_FAN = 6

COMPONENT_TYPE_ENUM = {
    COMPONENT_TYPE_BYTE: "b",
    COMPONENT_TYPE_UNSIGNED_BYTE: "B",
    COMPONENT_TYPE_SHORT: "h",
    COMPONENT_TYPE_UNSIGNED_SHORT: "H",
    COMPONENT_TYPE_UNSIGNED_INT: "I",
    COMPONENT_TYPE_FLOAT: "f",
}

NUM_COMPONENTS_BY_TYPE_ENUM = {
    TYPE_SCALAR: 1,
    TYPE_VEC2: 2,
    TYPE_VEC3: 3,
    TYPE_VEC4: 4,
    TYPE_MAT2: 4,
    TYPE_MAT3: 9,
    TYPE_MAT4: 16,
}

MODE_BY_VERTEX_COUNT = {
    3: None,
    2: 1,
    1: 0,
}

VERTEX_COUNT_BY_MODE = {
    MODE_POINTS: 1,
    MODE_LINES: 2,
    MODE_TRIANGLES: 3,
    None: 3,
}
